# Generated by Django 4.2 on 2023-04-10 10:04

import accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,10}$')])),
                ('image', models.ImageField(default='user_default_avatar.png', upload_to='profile_pic')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('age', models.DateField(blank=True, null=True, validators=[accounts.validators.MinAgeValidator(13)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('medical_number', models.CharField(max_length=7)),
                ('specialist', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0.0)),
                ('rate_counter', models.IntegerField(default=0)),
                ('diseases', models.CharField(choices=[('شخصیت خودشیف', 'اختلال شخصیت خودشیف'), ('وسواس', 'وسواس'), ('کابوس', 'اختلال کابوس شبانه'), ('هویت', 'اختلال هویت جنسیتی'), ('هیستری', 'هیستری'), ('پرخوابی', 'پرخوابی ایدیوپاتیک'), ('بی\u200cخوابی', 'بی\u200cخوابی'), ('نافرمانی', 'اختلال نافرمانی مقابله جویانه'), ('خلقی', 'اختلال خلقی فصلی'), ('اسکیزوفرنی', 'اسکیزوفرنی'), ('نشخوار فکری', 'نشخوار فکری'), ('شخصیت اسکیزوتایپال', 'اختلال شخصیت اسکیزوتایپال'), ('فوبیای اجتماعی', 'فوبیای اجتماعی'), ('بی اختیاری عاطفی', 'بی اختیاری عاطفی'), ('شخصیت پارانوئید', 'اختلال شخصیت پارانوئید'), ('هراس', 'اختلال هراس'), ('اضطراب', 'اختلال اضطراب پس از سانحه'), ('پرخوری', 'اختلال پرخوری'), ('دوقطبی', 'اختلال دوقطبی'), ('شخصیت مرزی', 'اختلال شخصیت مرزی')], max_length=18)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
