export const DOCTORS_LIST_REQUEST = "DOCTORS_LIST_REQUEST";
export const DOCTORS_LIST_SUCCESS = "DOCTORS_LIST_SUCCESS";
export const DOCTORS_LIST_FAIL = "DOCTORS_LIST_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";

