export const DOCTORS_LIST_REQUEST = "DOCTORS_LIST_REQUEST";
export const DOCTORS_LIST_SUCCESS = "DOCTORS_LIST_SUCCESS";
export const DOCTORS_LIST_FAIL = "DOCTORS_LIST_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";

export const USER_PROFILE_DR_REQUEST = "USER_PROFILE_DR_REQUEST";
export const USER_PROFILE_DR_SUCCESS = "USER_PROFILE_DR_SUCCESS";
export const USER_PROFILE_DR_FAIL = "USER_PROFILE_DR_FAIL";
export const USER_PROFILE_DR_RESET="USER_PROFILE_DR_RESET";

export const USER_EDIT_PROFILE_DR_REQUEST="USER_EDIT_PROFILE_DR_REQUEST";
export const USER_EDIT_PROFILE_DR_SUCCESS="USER_EDIT_PROFILE_DR_SUCCESS";
export const USER_EDIT_PROFILE_DR_FAIL="USER_EDIT_PROFILE_DR_FAIL";
export const USER_EDIT_PROFILE_DR_RESET="USER_EDIT_PROFILE_DR_RESET";

