export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_DR_REQUEST = "USER_REGISTER_DR_REQUEST";
export const USER_REGISTER_DR_SUCCESS = "USER_REGISTER_DR_SUCCESS";
export const USER_REGISTER_DR_FAIL = "USER_REGISTER_DR_FAIL";

export const USER_REGISTER_PATIENT_REQUEST = "USER_REGISTER_PATIENT_REQUEST";
export const USER_REGISTER_PATIENT_SUCCESS = "USER_REGISTER_PATIENT_SUCCESS";
export const USER_REGISTER_PATIENT_FAIL = "USER_REGISTER_PATIENT_FAIL";

export const USER_REGISTER_VERIFY_REQUEST = "USER_REGISTER_VERIFY_REQUEST";
export const USER_REGISTER_VERIFY_SUCCESS = "USER_REGISTER_VERIFY_SUCCESS";
export const USER_REGISTER_VERIFY_FAIL = "USER_REGISTER_VERIFY_FAIL";

export const USER_REGISTER_GET_ADMIN_REQUEST =
  "USER_REGISTER_GET_ADMIN_REQUEST";
export const USER_REGISTER_GET_ADMIN_SUCCESS =
  "USER_REGISTER_GET_ADMIN_SUCCESS";
export const USER_REGISTER_GET_ADMIN_FAIL = "USER_REGISTER_GET_ADMIN_FAIL";

export const USER_REGISTER_SEND_ADMIN_REQUEST =
  "USER_REGISTER_SEND_ADMIN_REQUEST";
export const USER_REGISTER_SEND_ADMIN_SUCCESS =
  "USER_REGISTER_SEND_ADMIN_SUCCESS";
export const USER_REGISTER_SEND_ADMIN_FAIL = "USER_REGISTER_SEND_ADMIN_FAIL";

export const USER_PROFILE_DR_REQUEST= "USER_PROFILE_DR_REQUEST";
export const USER_PROFILE_DR_SUCCESS="USER_PROFILE_DR_SUCCESS";
export const USER_PROFILE_DR_FAIL= "USER_PROFILE_DR_FAIL";