# Generated by Django 4.2 on 2023-04-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('medical_number', models.CharField(max_length=7)),
                ('specialist', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
